var r_text = new Array (); 
r_text[0] = "Use uBlock Origin to block ads/trackers when browsing the web."; 
r_text[1] = "Don't use Windows, try Linux instead."; 
r_text[2] = "Avoid CloudFlare along with websites that rely on them."; 
r_text[3] = "Use the Tor Browser as much as possible."; 
r_text[4] = "Just because you use a VPN, it doesn't make you safe. Use a trusted one."; 
r_text[5] = "Use privacy friendly alternatives. Check ThinkPrivacy.io";
r_text[6] = "Use Schiffer.Tech to protect your screen, keyboard, and webcam from capture. Windows/Android.";
r_text[7] = "If you need a good privacy guide, check out PrivacyTools.io";
r_text[8] = "Never trust a company like Google (YouTube) or Facebook (WhatsApp).";
r_text[9] = "Self hosting is a better option if possible. Never trust your files/info on someone else's server.";
r_text[10] = "Protect your Android device's camera from unwanted capture. Check out glitcher32.com/camerablocker";
r_text[11] = "A privacy phone OS is /e/OS. Check them out at e.foundation";
r_text[12] = "The safest place to store info is in your brain.";
r_text[13] = "Cryptomator is a great client-side file encryption software for all devices!";
r_text[14] = "Don't use any security system connected to a server not owned by you.";
r_text[15] = "F-Droid and Aurora Store are good Google Play Store alternatives.";
r_text[16] = "Signal and Wire are both great messaging apps.";
r_text[17] = "Invidious is a great alternative front-end to YouTube. Checkout invidio.us or invidious.snopyta.org";
r_text[18] = "Never share ANY of your personal information online anywhere. Such as name, phone number, or even email.";
r_text[19] = "Something as little as your name, username, email, phone number, etc. can be tracked to you and everything about you.";
r_text[20] = "Tor Browser, Fennec F-Droid, and Privacy Browser are good Android browsers to use.";
r_text[21] = "If you download torrents, you're download history might be public! Check it out at iknowwhatyoudownload.com";
var i = Math.floor(r_text.length * Math.random()); 
document.write("<b>[Privacy Tip]</b> " + 
r_text[i]  + "</FONT></center><br />"); 
